packageExtensions:
  iconv-lite@*:
    dependencies:
      buffer: ^6
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
  "@docusaurus/theme-search-algolia@*":
    dependencies:
      "@algolia/client-search": ^4.9.1
      prism-react-renderer: ^1.2.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.2.2.cjs

changesetIgnorePatterns:
  - "**/*.spec.{ts,tsx}"
  - "**/*.test.{ts,tsx}"
  - "example/**/*"
  - "website/**/*"
