changesetIgnorePatterns:
  - "**/*.spec.{ts,tsx}"
  - "**/*.test.{ts,tsx}"
  - example/**/*
  - e2e-tests/**/*

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  iconv-lite@*:
    dependencies:
      buffer: ^6

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

preferReuse: true
