changesetIgnorePatterns:
  - "**/*.spec.{ts,tsx}"
  - "**/*.test.{ts,tsx}"
  - example/**/*

compressionLevel: mixed

enableGlobalCache: true

pnpEnableEsmLoader: true

nodeLinker: node-modules

packageExtensions:
  iconv-lite@*:
    dependencies:
      buffer: ^6

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
